# Generated by Django 3.1.3 on 2020-11-19 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questlog', '0004_questlogcontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestLogContent',
        ),
    ]
